quarkus:
  http:
    port: 8080
  datasource:
    db-kind: mysql
    username: root
    password: root
    reactive:
      ~: true
      url: mysql://localhost:3306/clean_architecture_quarkus_db
  mailer:
    from: test@quarkus.io
    host: smtp.sendgrid.net
    port: 465
    ssl: true
    username: mock
    password: mock
    mock: true

flyway_migration:
  url: jdbc:mysql://localhost:3306/clean_architecture_quarkus_db
  username: root
  password: root

managed-executor:
  max-async: 5